/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.std;

import java.io.IOException;
import java.net.SocketException;
import java.net.UnknownHostException;

public class App {

    public static void main(String[] args) throws SocketException, UnknownHostException, IOException {
        ServidorTcp servidorTcp = new ServidorTcp();
        servidorTcp.executar(args);
    }
}
